@startuml Game Domain Model
skinparam classBackgroundColor #F8F8F8
skinparam classAttributeIconSize 0
skinparam classAttributeFontSize 16

' może dodać coś jeszcze?
class Gra {
  + gracze : List<Gracz>
  + planszaEpoki : PlanszaEpoki
  + planszaKonfliktu : PlanszaKonfliktu
  + stanGry : StanGry
  ' + aktywnyGracz : Gracz
  + stosKartOdrzuconych : List<Karta>
  + CzyKoniecGry() : bool
  + WykonajRuch(ruch : Ruch) : void
  + Clone() : Gra
}

class Gracz {
  + nazwa : string
  + kartyCudu : List<KartaCudu>
  + zbudowaneKarty : List<Karta>
  + surowce : Dictionary<Surowiec, int>
  + punktyZwyciestwa : int
  + efekty : List<Efekt>
  + symboleNaukowe : List<SymbolNaukowy>
  + zetonyPostepu : List<ZetonPostepu>
}

class StanGry {
  + czyZakonczona : bool
  + typZwyciestwa : TypZwyciestwa
  + zwyciezca : Gracz
}

class PlanszaEpoki {
  + epoka : Epoka
  + pola : List<PoleKarty>
}

class PoleKarty {
  + karta : Karta
  + czyZakryta : bool
  + blokujacePola : List<PoleKarty>
}

class PlanszaKonfliktu {
  + pion : PionKonfliktu
  + strefy : List<Strefa>
  + zetonyPostepu : List<ZetonPostepu>
}

class PionKonfliktu {
  + pozycja : int
  ' + PrzesunPion() : void
}

class Strefa {
  + nazwa : string
  + liczbaPol : int
  + punkty : int
  + traconeMonety : int
  + czyZajeta : bool
  + czyJuzUzyta : bool
}

abstract class KartaBazowa {
  + nazwa : string
  + koszt : Dictionary<Surowiec, int>
  + efekty : List<Efekt>
}

class Karta {
  + epoka : int
  + kolor : KolorKarty
  + czyZagrana : bool
  + czyOdrzucona : bool
  + czyWidoczna : bool
}

class KartaCudu {
  + czyZagrana : bool
}

class ZetonPostepu {
  + nazwa : string
  + efekty : List<Efekt>
}

' class Efekt {
'   + typEfektu : TypEfektu
'   + wartosc : int
'   + surowce : Dictionary<Surowiec, int>
'   + tekst : string
' }

KartaBazowa <|-- Karta
KartaBazowa <|-- KartaCudu

Gra "1" *-- "2" Gracz : gracze
Gra "1" *-- "1" PlanszaEpoki : planszaEpoki
Gra "1" *-- "1" PlanszaKonfliktu : planszaKonfliktu
Gra "1" *-- "1" StanGry : stanGry
Gra "1" o-- "*" Karta : stosKartOdrzuconych

Gracz "1" o-- "*" Karta : zbudowaneKarty
Gracz "1" o-- "*" KartaCudu : kartyCudu
' Gracz "1" o-- "*" Efekt : efekty
Gracz "1" o-- "*" ZetonPostepu : zetonyPostepu

PlanszaEpoki "1" *-- "*" PoleKarty : pola
PoleKarty "1" --> "1" Karta : karta

PlanszaKonfliktu "1" *-- "1" PionKonfliktu : pion
PlanszaKonfliktu "1" *-- "*" Strefa : strefy
PlanszaKonfliktu "1" o-- "*" ZetonPostepu : zetonyPostepu

' KartaBazowa "1" *-- "*" Efekt : efekty
' ZetonPostepu "1" *-- "*" Efekt : efekty

StanGry --> Gracz : zwyciezca
@enduml