@startuml Genetic Algorithm Model
skinparam ActivityBackgroundColor #E8F4FD
' skinparam ActivityBorderColor #2980B9
skinparam ActivityDiamondBackgroundColor #FEF9E7
' skinparam ActivityDiamondBorderColor #F39C12
skinparam NoteBackgroundColor #FFF9E6
skinparam NoteBorderColor #F39C12

start

' partition "1. Wygenerowanie podstawowej populacji" {
  :Generacja początkowej populacji osobników 
  (losowe wagi z zakresu [1.0, 15.0]);
  note right
    PunktyZwycięstwa = 10.0
  end note
' }

' partition "2. Pętla treningowa" {
  repeat
    :Ocena populacji (Funkcja oceny);
    note right
      Rozgrywanie partii z przeciwnikiem:
      Pierwsza iteracja - Agent Losowy
      Kolejne iteracji: najlepszy osobnik z poprzedniej iteracji
    end note

    :Sortowanie populacji;
    note right
      Według liczby zwycięstw w porządku malejącym
    end note

    if (Najlepszy osobnik > 50% zwycięstw?) then (tak)
      :Aktualizacja najlepszego osobnika;
    else (nie)
    endif

    :Utworzenie nowej populacji;
    note right
      2 najlepszych osobników + mutacja najlepszego
      (dodanie losowej liczby z zakresu [-2.0, 2.0])
    end note

  repeat while (Są kolejne iteracje?) is (tak)
  ->nie;
' }

:Zapisanie najlepszego osobnika;

stop
@enduml