<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="8.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

	<!--<ItemGroup>
		<Compile Include="..\7 Wonders\Assets\Scripts\Core\**\*.cs" Link="Core\%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="..\7 Wonders\Assets\Scripts\Core\KartyEpoki\RozkladKart.cs" />
	</ItemGroup>-->

	<ItemGroup>
		<ProjectReference Include="..\GameCore\GameCore.csproj" />
		<ProjectReference Include="..\GameAI\GameAI.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="EncoderResults\" />
	  <Folder Include="TestResults\" />
	</ItemGroup>

</Project>
