<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\GameCore\GameCore.csproj" />
		<ProjectReference Include="..\GameAI\GameAI.csproj" />
	</ItemGroup>

    <!--<ItemGroup>
	    <Compile Include="..\7 Wonders\Assets\Scripts\Core\**\*.cs" Link="Core\%(RecursiveDir)%(Filename)%(Extension)" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="..\7 Wonders\Assets\Scripts\Core\KartyEpoki\RozkladKart.cs" />
    </ItemGroup>-->

</Project>
